MVCproject/MVCproject.WEB/Models/PizzaTypeViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MVCproject.WEB.Models
{
    public class PizzaTypeViewModel
    {
        [Required]
        [HiddenInput(DisplayValue = false)]
        public int PizzaTypeID { get; set; }

        [Required(ErrorMessage = "Поле должно быть заполнено.")]
        [DisplayName("Цена")]
        [Range(1, 10000, ErrorMessage = "Значение от 1 до 10000")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Поле должно быть заполнено.")]
        [DisplayName("Масса")]
        [Range(1, 10000, ErrorMessage = "Значение от 1 до 10000")]
        public int Weight { get; set; }

        [Required(ErrorMessage = "Поле должно быть заполнено.")]
        [DisplayName("Диаметр")]
        [Range(1, 10000, ErrorMessage = "Значение от 1 до 10000")]
        public int Diameter { get; set; }

        [Required]
        [HiddenInput(DisplayValue = false)]
        public int PizzaID { get; set; }
    }
}

MVCproject/MVCproject.WEB/Controllers/PizzaTypeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MVCproject.BLL.Interfaces;
using MVCproject.BLL.Models;
using MVCproject.WEB.Models;

namespace MVCproject.WEB.Controllers
{
    [RoutePrefix("Type")]
    [Authorize(Roles = "Admin")]
    public class PizzaTypeController : Controller
    {
        private readonly IPizzaTypeService _pizzaTypeService;

        public PizzaTypeController(IPizzaTypeService serv)
        {
            _pizzaTypeService = serv;
        }

        
        [Route("View")]
        [AllowAnonymous]
        public ActionResult View(int? pizzaid)
        {
            IEnumerable<PizzaTypeDTO> pizzaTypeDtos = _pizzaTypeService.GetPizzaTypesByPizzaId(pizzaid.Value);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<PizzaTypeDTO, PizzaTypeViewModel>()).CreateMapper();
            var pizzatypes = mapper.Map<IEnumerable<PizzaTypeDTO>, List<PizzaTypeViewModel>>(pizzaTypeDtos);
            ViewBag.pizzaid = pizzaid;
            return View(pizzatypes);
        }


        [HttpGet]
        [Route("Edit-{id}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            PizzaTypeDTO pizzaTypeDto = _pizzaTypeService.GetPizzaType(id);

            if (pizzaTypeDto != null)
            {
                PizzaTypeViewModel pizzaTypeViewModel = new PizzaTypeViewModel()
                {
                    PizzaID = pizzaTypeDto.PizzaID,
                    Diameter = pizzaTypeDto.Diameter,
                    Price = pizzaTypeDto.Price,
                    Weight = pizzaTypeDto.Weight,
                    PizzaTypeID = pizzaTypeDto.PizzaTypeID
                };

                return PartialView(pizzaTypeViewModel);
            }
            return HttpNotFound();
        }


        [HttpPost]
        [Route("Edit-{id}")]
        public ActionResult Edit(PizzaTypeViewModel pizzaTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                PizzaTypeDTO pizzaTypeDto = new PizzaTypeDTO()
                {
                    PizzaID = pizzaTypeViewModel.PizzaID,
                    Diameter = pizzaTypeViewModel.Diameter,
                    PizzaTypeID = pizzaTypeViewModel.PizzaTypeID,
                    Price = pizzaTypeViewModel.Price,
                    Weight = pizzaTypeViewModel.Weight
                };

                _pizzaTypeService.UpdatePizzaType(pizzaTypeDto);
                return RedirectToAction("Index", "PizzaCategory");
            }
            return View("Edit", pizzaTypeViewModel);
        }


        [HttpGet]
        [Route("Delete-{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            PizzaTypeDTO pizzaTypeDto = _pizzaTypeService.GetPizzaType(id);

            if (pizzaTypeDto != null)
            {
                PizzaTypeViewModel pizzaTypeViewModel = new PizzaTypeViewModel()
                {
                    PizzaID = pizzaTypeDto.PizzaID,
                    Diameter = pizzaTypeDto.Diameter,
                    Price = pizzaTypeDto.Price,
                    Weight = pizzaTypeDto.Weight,
                    PizzaTypeID = pizzaTypeDto.PizzaTypeID
                };

                return PartialView(pizzaTypeViewModel);
            }
            return RedirectToAction("Index", "PizzaCategory");
        }


        [Route("Delete-{id}")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            PizzaTypeDTO pizzaTypeDto = _pizzaTypeService.GetPizzaType(id);
            if (pizzaTypeDto != null)
            {
                _pizzaTypeService.DeletePizzaType(id.Value);
            }
            return RedirectToAction("Index", "PizzaCategory");
        }


        [HttpGet]
        [Route("Create-{id}")]
        public ActionResult Create(int? id)
        {
            return PartialView(new PizzaTypeViewModel()
            {
                PizzaID = id.Value
            });
        }

        [HttpPost]
        [Route("Create-{id}")]
        public ActionResult Create(PizzaTypeViewModel pizzaTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                PizzaTypeDTO pizzaTypeDto = new PizzaTypeDTO()
                {
                    PizzaID = pizzaTypeViewModel.PizzaID,
                    Diameter = pizzaTypeViewModel.Diameter,
                    PizzaTypeID = pizzaTypeViewModel.PizzaTypeID,
                    Price = pizzaTypeViewModel.Price,
                    Weight = pizzaTypeViewModel.Weight
                };

                _pizzaTypeService.CreatePizzaType(pizzaTypeDto);
                return RedirectToAction("Index", "PizzaCategory");
            }
            return PartialView("Create", pizzaTypeViewModel);
        }

    }
}

MVCproject/MVCproject.WEB/Views/PizzaType/Create.cshtml
@model MVCproject.WEB.Models.PizzaTypeViewModel
@{
    Layout = null;
}



<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Добавление нового типа</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

        @using (Html.BeginForm("Create", "PizzaType", FormMethod.Post))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Diameter, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Diameter, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Diameter, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.PizzaID)
                @Html.HiddenFor(model => model.PizzaTypeID)
                
                <div class="modal-footer">
                        <input type="submit" value="Добавить" class="btn btn-default" />
                        <button class="btn btn-light" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        }

MVCproject/MVCproject.WEB/Views/PizzaType/Delete.cshtml
@model MVCproject.WEB.Models.PizzaTypeViewModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel"> Вы действительно хотите удалить данный тип?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

    @Html.Label("Diameter", "Размер: " + Model.Diameter + "см, ")
    @Html.Label("Price", "Цена: " + Model.Price + " руб, ")
    @Html.Label("Weight", "Масса: " + Model.Weight + "г.")
    @using (Html.BeginForm())
    {
        
        <div class="modal-footer">
                <input type="submit" value="Удалить" class="btn btn-default" />
                <button class="btn btn-light" data-dismiss="modal">Закрыть</button>
        </div>
    }

MVCproject/MVCproject.WEB/Views/PizzaType/Edit.cshtml
@model MVCproject.WEB.Models.PizzaTypeViewModel



<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Редактирование типа</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

@using (Html.BeginForm())
        {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Diameter, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Diameter, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Diameter, "", new { @class = "text-danger" })
                </div>
            </div>
                @Html.HiddenFor(model=>model.PizzaID)
                @Html.HiddenFor(model=>model.PizzaTypeID)
            
            <div class="modal-footer">
                <input type="submit" value="Изменить" class="btn btn-default" />
                <button class="btn btn-light" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
        }

MVCproject/MVCproject.WEB/Views/PizzaType/View.cshtml
@model List<MVCproject.WEB.Models.PizzaTypeViewModel>

@{
    Layout = null;
}

<div id="pizzaTypeWrapper">
    @for (int i = 0; i < Model.Count; i++)
    {
    <div class="btn-group w-100 m-1" role="group">
        @if (User.IsInRole("User"))
        {
            @(Ajax.ActionLink("Закзать", "AddToCart", "Cart", new { id = Model[i].PizzaTypeID }, new AjaxOptions()
        {
            HttpMethod = "Get",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "modal-content",
            OnSuccess = "$.validator.unobtrusive.parse('form');",
            AllowCache = false
        }, new { @class = "btn btn-sm btn-success", @style = "", data_toggle = "modal", data_target = "#exampleModal" }))
        }

        <button type="button" class="btn btn-sm btn-success container" disabled>
            <b>@Model[i].Price</b> руб, <b>@Model[i].Diameter</b> см, <b>@Model[i].Weight</b> г.
        </button>
        
        @if (User.IsInRole("Admin"))
        {
            @Ajax.ActionLink("clear", "Delete", "PizzaType", new {id = Model[i].PizzaTypeID}, new AjaxOptions()
            {
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "modal-content",
                AllowCache = false
            }, new {@class = "btn btn-sm btn-warning material-icons", @style = " color: white", data_toggle = "modal", data_target = "#exampleModal" })


            @Ajax.ActionLink("create", "Edit", "PizzaType", new {id = Model[i].PizzaTypeID}, new AjaxOptions()
           {
               HttpMethod = "Get",
               InsertionMode = InsertionMode.Replace,
               UpdateTargetId = "modal-content",
               OnSuccess = "$.validator.unobtrusive.parse('form');",
               AllowCache = false
           }, new {@class = "btn btn-sm btn-warning material-icons", @style = "color: white", data_toggle = "modal", data_target = "#exampleModal" })
            }   

    </div>
    }
    

    @if (User.IsInRole("Admin"))
    {
        @Ajax.ActionLink("add", "Create", "PizzaType", new {id = ViewBag.pizzaid}, new AjaxOptions()
        {
            HttpMethod = "Get",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "modal-content",
            OnSuccess = "$.validator.unobtrusive.parse('form');",
            AllowCache = false
        }, new {@class = "btn btn-sm btn-warning material-icons w-100 m-1", @style = "font-size:16px; color: white", data_toggle = "modal", data_target = "#exampleModal" })
    }


</div>